spring:
  config:
    activate:
      on-profile: local

social:
  client:
    kakao:
      rest-api-key: e63a09d1b9408d34cb9abec225d3b162
      secret-key: r4HTzeCKl1mKDwpkMxSuj7BcP1lyhqNo
      redirect-uri: http://localhost:8080/api/v1/user/kakao-login
      grant_type: authorization_code

jwt:
  password: sdfasdfasfdaasdfsdfasdfasfdaasdf