spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.h2.Driver
#    url: jdbc:mysql://localhost:8082/test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  profiles:
    default: local

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html