@startuml
'https://plantuml.com/sequence-diagram

autonumber

group Step 1: 인가 코드 받기
    ServiceClient -> ServiceServer : 카카오 로그인 요청
    ServiceServer -> KakaoAuthServer : GET /oauth/authorize
    KakaoAuthServer -> ServiceClient : 카카오 연동 로그인 요청
    ServiceClient -> KakaoAuthServer : 카카오 계정 이용한 연동 로그인
    KakaoAuthServer -> ServiceServer : 302 Redirect URI로 이동 및 query parameter로 인가 code 전달
end
group Step 2: 토큰 받기
    ServiceServer -> KakaoAuthServer : POST /oauth/token (인가 code 이용)
    KakaoAuthServer -> ServiceServer : 토큰 발급 (사용자 정보 조회에 사용)
end

group Step 3: 사용자 로그인 처리
    ServiceServer -> ServiceServer : 발급받은 토큰을 이용해 사용자 정보 조회 및 기타 작업
    ServiceServer -> ServiceClient : 로그인 완료
end
@enduml